# Generated by Django 2.2.2 on 2019-06-28 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PhotoApp', '0002_auto_20190628_0200'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='conver',
            field=models.TextField(default=None, max_length=200),
            preserve_default=False,
        ),
    ]
