# Generated by Django 2.2.2 on 2019-06-28 02:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PhotoApp', '0003_post_conver'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='conver',
            new_name='cover',
        ),
    ]
