# Generated by Django 2.2.2 on 2019-07-01 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PhotoApp', '0005_auto_20190628_0203'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='cover',
        ),
    ]
