# Generated by Django 2.2.2 on 2019-07-03 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PhotoApp', '0007_auto_20190701_2258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='description',
            field=models.TextField(default=None, max_length=200),
        ),
    ]
