# Generated by Django 2.2.3 on 2019-07-10 05:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('PhotoApp', '0009_post_app_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default=None, max_length=250, null=True)),
                ('year', models.CharField(blank=True, default=None, max_length=250, null=True)),
                ('description', models.CharField(blank=True, default=None, max_length=250, null=True)),
                ('app_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('images', models.ManyToManyField(blank=True, default=None, null=True, to='PhotoApp.Post')),
            ],
        ),
    ]
