# Generated by Django 2.2.3 on 2019-07-10 22:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PhotoApp', '0011_auto_20190710_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='album',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Album', to='PhotoApp.Album'),
        ),
    ]
