# Generated by Django 2.2.3 on 2019-07-12 03:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PhotoApp', '0013_remove_album_album_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='album_images',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post_images', to='PhotoApp.Post'),
        ),
    ]
