# Generated by Django 2.2.3 on 2019-07-12 03:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PhotoApp', '0014_album_album_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='album_images',
        ),
    ]
