# Generated by Django 2.2.3 on 2019-07-22 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PhotoApp', '0015_remove_album_album_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='album_year',
            field=models.DecimalField(blank=True, decimal_places=0, default=None, max_digits=4, null=True),
        ),
    ]
